version: "2"

networks:
  workmotion-network:
    driver: bridge

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    networks:
      - workmotion-network
    restart: unless-stopped
    volumes:
    - ./schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    - ./schema_2.sql:/docker-entrypoint-initdb.d/2-schema_2.sql
    environment:
      POSTGRES_USER: dimas
      POSTGRES_PASSWORD: password
      POSTGRES_DB: employee
    depends_on:
      - postgress




